### ISSUE TITLE
[ShowCharacterInfo] Only displays the Unicode value, but not the name or the character itself

### ISSUE THREAD

**Issue by robinsdg** [FontBureau/fbOpenTools#14]

**Comment by rbmntjs** [comment]
FWIW, it’s line 122 in `showCharacterInfo.py`, and you just need to replace `unichr()` with `chr()` – worth a fix to bring it truly in line with Python 3.

**Comment by djrrb** [comment]
Yikes, sorry for not seeing this issue sooner...such an easy fix! I’ve committed this in 705f42d18e59a6ec02502c60d7e5c67ad30f5c42 but am traveling now and unable to test it. Let me know if there are any more issues here!

**Comment by rbmntjs** [comment]
Thanks! That’s all I changed on my side and it fixed it. This could be updated with a new version, but I haven’t tested it in Python 2 environments, could be a single import from `builtins`, but I’m not an adventurer.
