### ISSUE TITLE
retired extensions

### ISSUE THREAD

**Issue by typemytype** [FontBureau/fbOpenTools#15]
should I remove them from Mechanic 2 as they now are listed but cause errors cause the paths are not set correctly

https://github.com/FontBureau/fbOpenTools/tree/master/Retired_Extensions

see https://github.com/robofont-mechanic/mechanic-2-server/blob/gh-pages/_data/showDelta.yml

**Comment by djrrb** [comment]
Yes @typemytype, that would be great to remove them from Mechanic.

* Show Delta has been superseded by [Show Mouse Coordinates](https://github.com/FontBureau/fbOpenTools/tree/master/ShowMouseCoordinates).

* And @ninastoessinger’s amazing [word-o-mat](https://github.com/ninastoessinger/word-o-mat) does everything that Random Word Generator does but better.

I will close this issue, but if I should change anything about the structure of this repository, let me know. Thank you!

**Comment by typemytype** [comment]
removed, thanks!
