### ISSUE TITLE
Show Mouse Coordinates: NameError: name 'unichr' is not defined​

### ISSUE THREAD

**Issue by BoldMonday** [FontBureau/fbOpenTools#17]
When using this extension in RF3.3 it will throw this error when a selection is dragged inside a glyph window:
```
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 129, in callObserver_withMethod_forEvent_withInfo_
  File "showMouseCoordinates.py", line 45, in mouseDragged
NameError: name 'unichr' is not defined​
```

Remedy: remove line 45 in showMouseCoordinates.py:
```positionSymbol = unichr(8982)```
The variable in question appears not to be used at all.

**Comment by djrrb** [comment]
Thanks for finding this @BoldMonday ! I think this was a byproduct from a different script, and an easy fix! Let me know if there are any other issues.
