### ISSUE TITLE
Italic Bowtie: multiple interface windows open in RF4

### ISSUE THREAD

**Issue by jeremymickel** [FontBureau/fbOpenTools#29]
In RF4, when you open Italic Bowtie it opens 7 interface windows instead of the expected 1.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/2964496/155436545-1ceed264-320f-477a-984e-a4840f1d5813.png">

**Comment by colinmford** [comment]
(more than 2 years later) @jeremymickel, PR #36 should fix this
