### ISSUE TITLE
[Show Character Info] Info changes opacity

### ISSUE THREAD

**Issue by ryanbugden** [FontBureau/fbOpenTools#32]
When a glyph editor is first opened, my text is black. When I change glyph it becomes the same-ish color as the font dimension labels.

<img width="243" alt="image" src="https://github.com/FontBureau/fbOpenTools/assets/12752088/a2f2e506-d441-48d5-a32a-83b4a5a1b9b9">
<img width="264" alt="image" src="https://github.com/FontBureau/fbOpenTools/assets/12752088/f1021024-1748-4e71-ae5e-8b8ec9c5aed1">

**Comment by djrrb** [comment]
Hmmm, not sure what would cause this. Tagging @roberto-arista in case this is related to e6ea22cf73bed87ae100a571571936c76a26a6f9

**Comment by ryanbugden** [comment]
It's no rush at all—super not important.

But I think it might be around [here](https://github.com/FontBureau/fbOpenTools/blob/e6ea22cf73bed87ae100a571571936c76a26a6f9/ShowCharacterInfo/ShowCharacterInfo.roboFontExt/lib/showCharacterInfo.py#L230).

Maybe if the default color is captured on `__init__`, and the color was set with a `glyphWindowDidOpen` observer, it might work to set the color sooner.

`getDefaultColor` could potentially happen on every `glyphWindowDidOpen` too, but I'm not sure how often people are changing their prefs.

Happy to PR if your prefer—just don't want to risk messing up any of the other folders or branches you might have going on.

**Comment by djrrb** [comment]
If you’re synced up with the repo, I don’t think there should be any issue if you PR. And yeah I’m so rusty on managing the RF interface that if you feel you have a good solve for this, I’ll happily accept!
